### ISSUE TITLE
Map everything using oatpp::Any and display results

### ISSUE THREAD

**Issue by roqerxz** [oatpp/oatpp-postgresql#16]
The following seems to no longer work:
`auto dataset = queryResult->fetch<oatpp::Vector<oatpp::Fields<oatpp::Any>>>();

/* Serialize result as a json string using json object mapper */
auto json = jsonObjectMapper.writeToString(dataset);

/* Print the resultant json */
std::cout << json->c_str() << std::endl;`

example from the doc: 
https://oatpp.io/docs/components/orm/#mapping-results

**Comment by lganzzzo** [comment]
Hello @roqerxz ,

Not working in what way? Any errors?

**Comment by lganzzzo** [comment]
Fixed in #17

**Comment by roqerxz** [comment]
great thanks for the quick turn around !
