### ISSUE TITLE
update conan-center repository to 1.2.5

### ISSUE THREAD

**Issue by erodriguezg** [oatpp/oatpp-postgresql#9]
Please can update the version to 1.2.5

https://conan.io/center/oatpp-postgresql

**Comment by lganzzzo** [comment]
Hello @erodriguezg ,

"Officially" oatpp is only distributed as a source code on Github.

The Conan builds are community maintained.
We do not maintain/update conan builds.

I would suggest asking Conan community for help or updating the package on your own.

Regards,
Leonid

**Comment by jgsogo** [comment]
I'm working on it here: https://github.com/conan-io/conan-center-index/pull/5723

**Comment by jgsogo** [comment]
Btw, are you planning to release a new `1.2.6` version with the Windows patch (https://github.com/oatpp/oatpp-postgresql/pull/8) or shall I apply it on the Conan recipe as well?

Thanks!

**Comment by lganzzzo** [comment]
Hey @jgsogo , 

> Btw, are you planning to release a new 1.2.6 version with the Windows patch (#8) or shall I apply it on the Conan recipe as well?

I would suggest taking the latest master. It's still `1.2.5` but with small fixes.
There will be no `1.2.6`. The next release is going to be `1.3.0`
